apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: showcase-templates
  description: A collection of Backstage templates for RH Summit
spec:
  type: url
  targets:
    - https://github.com/rhdhdemo/backstage-workshop/blob/main/scaffolder-templates/poi-backend/template.yaml
    - https://github.com/rhdhdemo/backstage-workshop/blob/main/scaffolder-templates/poi-gateway/template.yaml
    - https://github.com/rhdhdemo/backstage-workshop/blob/main/scaffolder-templates/poi-map/template.yaml
